import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { getFontNamesFromCss, buildGoogleFontsUrl } from "@/lib/get-css-fonts";
import "./globals.css";

// ─── To change fonts ─────────────────────────────────────────────────────────
// Update  :root { --font-sans / --font-serif / --font-mono }  in globals.css.
// This server component reads those values at render time and automatically
// loads the matching Google Font — no changes to layout.tsx needed.
// ─────────────────────────────────────────────────────────────────────────────

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fontNames = getFontNamesFromCss();
  const fontUrl = buildGoogleFontsUrl(fontNames);

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {fontUrl && (
          <>
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link
              rel="preconnect"
              href="https://fonts.gstatic.com"
              crossOrigin="anonymous"
            />
            <link rel="stylesheet" href={fontUrl} />
          </>
        )}
      </head>
      <body className="font-sans antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TooltipProvider>
            {children}
            <Toaster />
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
